# learning numpy

In [1]:
print("hello numpy")

hello numpy


In [1]:
import numpy as np

# 2d arr
arr2d=np.array([[1,2,3,4],[5,6,7,8]])
# resize arr
resize_arr=arr2d.reshape(4,2)
print(arr2d,arr2d.shape,resize_arr,resize_arr.shape,resize_arr.size)

[[1 2 3 4]
 [5 6 7 8]] (2, 4) [[1 2]
 [3 4]
 [5 6]
 [7 8]] (4, 2) 8


In [2]:
a=np.arange(0,10,1).reshape(2,5)
print(a)
np.ones((3,4),dtype=int)


[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [3]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
### Numpy vectorized operation
arr1 = np.array([1,2,3,4])
arr2 = np.array([10,20,30,40])

print(f"add: {arr1+arr2}")
print(f"add: {arr1.reshape(2,2)+arr2.reshape(2,2)}")




add: [11 22 33 44]
add: [[11 22]
 [33 44]]


In [5]:
### Universal function
arr=np.array([2,3,4,5,6])
print(np.sqrt(arr))
print(np.sin(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


In [6]:
random_arr=np.array([[1,2],[3,4],[5,6]])
random_arr[1:,1:]

array([[4],
       [6]])